### ISSUE TITLE
[Discussion] No longer recommended to import modules from deno.land/x

### ISSUE THREAD

**Issue by zhmushan** [zhmushan/abc#101]
> ### Can I edit or remove a module on deno.land/x?
> Module versions are persistent and immutable. It is thus not possible to edit or delete a module (or version), to prevent breaking programs that rely on this module. Modules may be removed if there is a legal reason to do (for example copyright infringement).

Just because I love `abc@v1`, and the Deno official registry forced me to use `abc@v1.0.2`. No other reasons.

**Comment by zhmushan** [comment]
I will also continue to maintain denolib.com

**Comment by zhmushan** [comment]
If someone disagrees, please state your reasons instead of "**just opposing**"

**Comment by marvinborner** [comment]
I honestly think that you should keep recommend deno.land/x. It's the default repository and therefore helps the popularity and usage of this project. I don't think that a few extra letters in the import (`1.0.2` instead of `v1`) are reason enough to not use deno.land/x anymore.
Anyways, even if you do that change I'm sure that the most people won't have any *real* problem with it. So - do what you think fits better.

**Comment by zhmushan** [comment]
Need to inform, I finally decided to continue to use the official Deno registry:
- An explicit version can reduce junk issues (some people can’t run the code just because they use the old version
- Smart developers know exactly how to change the registry
- The code from the official registry is more trustworthy (because you won't know whether my lovely cat will overwrite the original tag
