### ISSUE TITLE
Abc.start doesn't return Promise<void> so it appears to never resolve

### ISSUE THREAD

**Issue by alexjamesmalcolm** [zhmushan/abc#49]
Line 51 of abc.ts claims to return a promise but as far as I can tell this never resolves. Is this supposed to resolve when the server is shutdown or when it finishes successfully starting?
```typescript
async start(addr: string | ServerConfig): Promise<void> {
```

**Comment by zhmushan** [comment]
It should be resolved when the server is shutdown. We just need to modify `this.server.listener.close();` to `this.server.close();` [here](https://github.com/zhmushan/abc/blob/master/abc.ts#L84), following code will print "exit" when "/true" is requested:
```ts
const app = abc();
app.get("/:var", c => {
  const variable = c.params.var;
  if (variable === "true") {
    app.close();
  }

  return variable;
});

await app.start({
  port: 8080
});

console.log("exit");
```
Welcome to send a pr!

**Comment by alexjamesmalcolm** [comment]
Ok, so the promise is resolved when the server closes. Do you think the design should stay the same or if the promise should resolve once all endpoints are up and accepting requests? Or if a hybrid approach should be used, and the promise resolves when the server closes but `.listen` accepts an onSuccess callback?

**Comment by zhmushan** [comment]
Currently I tend to keep the original design.

For adding new APIs, we need to consider whether this change brings more convenience or more complexity. In my opinion, if the server fails to start, an exception should be thrown directly instead of using `onSuccess` or` onError` and other APIs to listen. If the server is shut down normally, the program will naturally execute the next line. Since there are countless situations to be considered in the real world, we cannot design a corresponding api for each situation. We should use Typescript itself to do as many things as possible, and behave more "naturally" than "designed".
