### ISSUE TITLE
route with extension

### ISSUE THREAD

**Issue by AvnerCohen** [zhmushan/abc#75]
It's is pretty common for web-frameworks to negotiate content via route extension.

```
app.get("/daysback/:days.json", ...
app.get("/daysback/:days.xml", ...
```

Any specific reason it is not supported? will you take contributions to support it ?

**Comment by zhmushan** [comment]
Unfortunately, the router will recognize `days.json` and `days.xml` as params, and we cannot register more than one wildcard in the same level of routing

**Comment by AvnerCohen** [comment]
Thanks @zhmushan I understand this is the case, trying to understand if this is intentional, or you plan to align abc to a more standard router?

My understanding is that this is a pretty common router pattern to use the extension to set the content type on the way back (I noticed that when sending js or css, content type is too not being set).

**Comment by zhmushan** [comment]
For further discussion of routing behavior, we need to wait for https://github.com/zhmushan/router/issues/1 to land.

Personally, I against match `:days.json`. Because it creates ambiguity: It is difficult to understand which character can correctly segment the params route.

Of course, before 1.0.0 I will make a decision whether to provide a custom router method.

At present, we can use the following methods to solve your needs:
```ts
app
  .get("/json_:days", (c) => c.path)
  .get("/xml_:days", (c) => c.path);
```
Or
```ts
app.get("/:days", (c) => {
  switch (c.path.split(".")[1]) {
    case "json": {
      break;
    }
    case "xml": {
      break;
    }
  }
});
```

**Comment by AvnerCohen** [comment]
Cool, I'll see what routes changes I can do to try and amend the behavior, I still think however, that there is value in doing routers in a standard way.
